### ISSUE TITLE
fix: 깃허브 인증 후 로그인 모달 닫기 

### ISSUE THREAD

**Issue by JungInHa** [codestates-seb/seb40_main_035#121]
##  💁 설명
닫도록 했는데,,, 닫히지 않고 있습ㄴ디ㅏ.
회원가입 페이지에서도 바로 로컬 스토리지 정보를 불러오지는 않고 있는 것 같아 확인이 필요합니다.

## 📑 작업해야 할 내용
- [ ] Todo1
- [ ] Todo2
- [ ] Todo3

## 🕰 예상 작업 시간
(ex. 3h)

**Comment by DalDalChoi** [comment]
![image](https://user-images.githubusercontent.com/107661312/205544096-ea27ee91-2507-462e-a435-0a93529b7ebf.png)
바로 그냥 closeLogIn 넣어보면 어떨까요 저는 테스트가 안됩니다 ㅎ,ㅎㅎ하핳ㅎ

**Comment by JungInHa** [comment]
헉 아 배포할 때 API 

> ![image](https://user-images.githubusercontent.com/107661312/205544096-ea27ee91-2507-462e-a435-0a93529b7ebf.png) 바로 그냥 closeLogIn 넣어보면 어떨까요 저는 테스트가 안됩니다 ㅎ,ㅎㅎ하핳ㅎ

헉 아 배포할 때 라우트 주소를 바꿔서 그런가봐요! app.js에서 RedirectGithub 연결된 주소에서 뒤에 .html을 빼줬습니당 그부분도 이슈로 생성해야겠네요!! 일단 closeLogIn() 해볼게요! 감사합니다ㅎㅎ
